# Generated by Django 4.1.5 on 2023-01-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='index_pnl',
            field=models.DecimalField(decimal_places=28, max_digits=50, verbose_name='Отношение чистых активов'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='net_assets',
            field=models.DecimalField(decimal_places=4, max_digits=50, verbose_name='Стоимость чистых активов'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='pnl',
            field=models.DecimalField(decimal_places=4, max_digits=50, verbose_name='Прибыль / убыток'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Курс доллара к биткоину'),
        ),
    ]
